/**
 * Auto-generated by product-studio/pipeline.py
 * Run with: yarn medusa exec src/scripts/seed-products-generated.ts
 *
 * Creates new products or updates images/thumbnail on existing ones.
 */

import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys, Modules } from "@medusajs/framework/utils"
import { createProductsWorkflow, updateProductsWorkflow } from "@medusajs/medusa/core-flows"

const STOREFRONT_URL =
  process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:8000"

const img = (handle: string, file: string) =>
  `${STOREFRONT_URL}/products/${handle}/${file}`

const PRODUCTS = [
  {
    title: "Black Botanical Kimono",
    handle: "black-botanical-kimono",
    subtitle: "Black crinkle kimono with all-over botanical floral print",
    description: "A chic and versatile open kimono in black crinkle-texture fabric with a delicate all-over botanical floral print in muted coral, green and yellow tones. Wide pleated sleeves and a relaxed open fit. Works beautifully as a layering piece over monochrome outfits or as a lightweight abaya alternative.",
    collection: "Kimonos",
    price_gbp: 42.0,
    sizes: ["S/M", "L/XL", "One Size"],
    thumbnail: img("black-botanical-kimono", "ai-02-lifestyle.jpg"),
    images: [
      img("black-botanical-kimono", "ai-02-lifestyle.jpg"),
      img("black-botanical-kimono", "ai-04-sofa.jpg"),
      img("black-botanical-kimono", "ai-01-folded.jpg"),
      img("black-botanical-kimono", "ai-03-macro.jpg"),
      img("black-botanical-kimono", "01-front.jpg"),
      img("black-botanical-kimono", "02-detail.jpg"),
    ],
  },
  {
    title: "Cream Leaf Print Kimono",
    handle: "cream-leaf-kimono",
    subtitle: "Relaxed open kimono in cream with bold botanical print",
    description: "A relaxed, effortlessly chic open kimono in cream with a bold botanical leaf print in warm rust and navy tones. The pleated crinkle fabric gives it a rich texture while keeping the silhouette light and airy. Wear open over black co-ords or belted for a more defined look.",
    collection: "Kimonos",
    price_gbp: 40.0,
    sizes: ["S/M", "L/XL", "One Size"],
    thumbnail: img("cream-leaf-kimono", "ai-02-lifestyle.jpg"),
    images: [
      img("cream-leaf-kimono", "ai-02-lifestyle.jpg"),
      img("cream-leaf-kimono", "ai-04-sofa.jpg"),
      img("cream-leaf-kimono", "ai-01-folded.jpg"),
      img("cream-leaf-kimono", "ai-03-macro.jpg"),
      img("cream-leaf-kimono", "01-front.jpg"),
      img("cream-leaf-kimono", "02-detail.jpg"),
    ],
  },
  {
    title: "Gold Shimmer Abaya",
    handle: "gold-shimmer-abaya",
    subtitle: "Statement open abaya in luxurious bronze-gold shimmer fabric",
    description: "Turn heads in this stunning bronze-gold shimmer open abaya. Crafted from a fluid, lightweight metallic fabric with an incredible drape, this floor-length piece is perfect for Eid celebrations, weddings, and formal occasions. The wide batwing sleeves and open-front silhouette create an effortlessly elegant look worn over any outfit.",
    collection: "Abayas",
    price_gbp: 45.0,
    sizes: ["S/M", "L/XL", "One Size"],
    thumbnail: img("gold-shimmer-abaya", "ai-02-lifestyle.jpg"),
    images: [
      img("gold-shimmer-abaya", "ai-02-lifestyle.jpg"),
      img("gold-shimmer-abaya", "ai-04-sofa.jpg"),
      img("gold-shimmer-abaya", "ai-01-folded.jpg"),
      img("gold-shimmer-abaya", "ai-03-macro.jpg"),
      img("gold-shimmer-abaya", "01-front.jpg"),
    ],
  },
  {
    title: "Grey Tassel Abaya",
    handle: "grey-tassel-abaya",
    subtitle: "Elegant grey crinkle abaya with signature tassel sleeves",
    description: "A beautifully textured open abaya in soft silver-grey crinkle fabric. The standout feature is the delicate tassel and tie detailing cascading from the sleeves, adding movement and a boho-luxe finish. Lightweight and breathable, this versatile piece transitions seamlessly from day to evening.",
    collection: "Abayas",
    price_gbp: 42.0,
    sizes: ["S/M", "L/XL", "One Size"],
    thumbnail: img("grey-tassel-abaya", "ai-02-lifestyle.jpg"),
    images: [
      img("grey-tassel-abaya", "ai-02-lifestyle.jpg"),
      img("grey-tassel-abaya", "ai-04-sofa.jpg"),
      img("grey-tassel-abaya", "ai-01-folded.jpg"),
      img("grey-tassel-abaya", "ai-03-macro.jpg"),
      img("grey-tassel-abaya", "01-front.jpg"),
      img("grey-tassel-abaya", "02-detail.jpg"),
    ],
  },
  {
    title: "Marble Fur-Trim Kimono",
    handle: "marble-fur-kimono",
    subtitle: "Abstract marble print kimono with faux fur trim",
    description: "A bold statement piece featuring a striking abstract marble-effect print in cream, rust and navy with dramatic dark faux fur trim running the full length of the opening. Wide flared cuffed sleeves and a floor-grazing length make this kimono unmistakably luxurious. Perfect for special occasions.",
    collection: "Kimonos",
    price_gbp: 48.0,
    sizes: ["S/M", "L/XL", "One Size"],
    thumbnail: img("marble-fur-kimono", "ai-02-lifestyle.jpg"),
    images: [
      img("marble-fur-kimono", "ai-02-lifestyle.jpg"),
      img("marble-fur-kimono", "ai-04-sofa.jpg"),
      img("marble-fur-kimono", "ai-01-folded.jpg"),
      img("marble-fur-kimono", "ai-03-macro.jpg"),
      img("marble-fur-kimono", "01-front.jpg"),
      img("marble-fur-kimono", "02-detail.jpg"),
    ],
  },
  {
    title: "Rose Butterfly Lace Kimono",
    handle: "rose-lace-kimono",
    subtitle: "Feminine dusty rose kimono with gold lace trim and butterfly sleeves",
    description: "Soft and romantic, this open kimono in dusty rose jersey is trimmed with delicate gold lace detail from neckline to hem. The butterfly-style sleeves create an elegant drape, and the tassel tie waist adds a feminine finishing touch. A bestseller for its versatility \u2014 perfect for Eid, weddings, or dressed-down everyday looks.",
    collection: "Kimonos",
    price_gbp: 38.0,
    sizes: ["S/M", "L/XL", "One Size"],
    thumbnail: img("rose-lace-kimono", "ai-02-lifestyle.jpg"),
    images: [
      img("rose-lace-kimono", "ai-02-lifestyle.jpg"),
      img("rose-lace-kimono", "ai-04-sofa.jpg"),
      img("rose-lace-kimono", "ai-01-folded.jpg"),
      img("rose-lace-kimono", "ai-03-macro.jpg"),
      img("rose-lace-kimono", "01-front.jpg"),
      img("rose-lace-kimono", "02-detail.jpg"),
    ],
  },
]

const SIZES = ["S/M", "L/XL", "One Size"]

export default async function seedGeneratedProducts({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const query = container.resolve(ContainerRegistrationKeys.QUERY)
  const productModuleService = container.resolve(Modules.PRODUCT)
  const salesChannelModuleService = container.resolve(Modules.SALES_CHANNEL)

  logger.info("Starting generated product seed...")

  const { data: regions } = await query.graph({
    entity: "region",
    fields: ["id", "name", "currency_code"],
  })

  const gbRegion =
    regions.find(
      (r: any) =>
        r.currency_code === "gbp" ||
        r.name?.toLowerCase().includes("uk") ||
        r.name?.toLowerCase().includes("gb")
    ) || regions[0]

  if (!gbRegion) {
    throw new Error("No region found. Run seed.ts first.")
  }

  const salesChannels = await salesChannelModuleService.listSalesChannels()
  const defaultChannel = salesChannels[0]

  const existingCollections =
    await productModuleService.listProductCollections()
  const collectionMap: Record<string, string> = {}

  for (const [title, handle] of [
    ["Abayas", "abayas"],
    ["Kimonos", "kimonos"],
    ["New In", "new-in"],
  ]) {
    const existing = existingCollections.find((c: any) => c.handle === handle)
    if (existing) {
      collectionMap[title] = existing.id
    } else {
      const created = await productModuleService.createProductCollections({
        title,
        handle,
      })
      collectionMap[title] = (created as any).id ?? (created as any)[0]?.id
    }
  }

  const existingProducts = await productModuleService.listProducts()
  const existingByHandle: Record<string, any> = {}
  for (const p of existingProducts) existingByHandle[p.handle] = p

  for (const product of PRODUCTS) {
    const existing = existingByHandle[product.handle]

    if (existing) {
      logger.info(`  Updating images: ${product.title}`)
      await updateProductsWorkflow(container).run({
        input: {
          selector: { id: existing.id },
          update: {
            thumbnail: product.thumbnail,
            images: product.images.map((url) => ({ url })),
          },
        },
      })
      logger.info(`  ✓ Updated: ${product.title}`)
      continue
    }

    logger.info(`  Creating: ${product.title}`)

    const { result } = await createProductsWorkflow(container).run({
      input: {
        products: [
          {
            title: product.title,
            handle: product.handle,
            subtitle: product.subtitle,
            description: product.description,
            status: "published" as const,
            thumbnail: product.thumbnail,
            images: product.images.map((url) => ({ url })),
            collection_id: collectionMap[product.collection],
            categories: [],
            tags: [],
            options: [{ title: "Size", values: SIZES }],
            variants: (product.sizes ?? SIZES).map((size) => ({
              title: size,
              sku: `${product.handle}-${size.toLowerCase().replace("/", "-")}`,
              options: { Size: size },
              prices: [
                {
                  amount: product.price_gbp,
                  currency_code: "gbp",
                  rules: { region_id: gbRegion.id },
                },
              ],
              manage_inventory: false,
            })),
            sales_channels: defaultChannel ? [{ id: defaultChannel.id }] : [],
          },
        ],
      },
    })

    logger.info(`  ✓ Created: ${result[0].title}`)
  }

  logger.info("✅ Generated product seed complete!")
}
