#!/usr/bin/env python3
"""
NikooLife Product Studio Pipeline

Processes product directories, generates AI lifestyle images, copies assets to
the storefront, and emits a ready-to-run Medusa seed script.

Usage:
  python pipeline.py                     # process all products in input/
  python pipeline.py <handle>            # process one product
  python pipeline.py <handle> --skip-ai  # copy images only, no AI generation

Each product folder inside input/ must contain:
  product.json   — product metadata (see input/example-product/product.json)
  01-front.jpg   — primary source image (required)
  02-detail.jpg  — detail / close-up source image (optional, improves fidelity)
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent.parent
STUDIO_DIR = Path(__file__).parent
INPUT_DIR = STUDIO_DIR / "input"
GENERATOR = ROOT / "ai-image-generator" / "generate_images.py"
STOREFRONT_PRODUCTS = ROOT / "storefront" / "public" / "products"
SEED_OUT = ROOT / "backend" / "src" / "scripts" / "seed-products-generated.ts"
STOREFRONT_URL_PLACEHOLDER = "${STOREFRONT_URL}"

# Maps generated style names → public-facing filenames
AI_IMAGE_MAP = {
    "folded-garment":     "ai-01-folded",
    "full-body-lifestyle": "ai-02-lifestyle",
    "close-up-macro":     "ai-03-macro",
    "spread-on-sofa":     "ai-04-sofa",
}

REQUIRED_SOURCE = "01-front"
OPTIONAL_DETAIL = "02-detail"


# ── Helpers ───────────────────────────────────────────────────────────────────

def find_image(directory: Path, stem: str) -> Path | None:
    for ext in (".jpg", ".jpeg", ".png", ".webp"):
        candidate = directory / f"{stem}{ext}"
        if candidate.exists():
            return candidate
    return None


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9-]", "-", text.lower()).strip("-")


def copy_source_images(product_dir: Path, out_dir: Path) -> list[str]:
    """Copy all non-JSON files from input dir to storefront product dir."""
    copied = []
    for f in sorted(product_dir.iterdir()):
        if f.suffix.lower() in (".jpg", ".jpeg", ".png", ".webp"):
            dest = out_dir / f.name
            shutil.copy2(f, dest)
            copied.append(f.name)
    return copied


def run_ai_generation(
    source: Path,
    detail: Path | None,
    out_dir: Path,
    high_thinking: bool = False,
) -> dict[str, str]:
    """Run the generator and return a map of style → filename in out_dir."""
    cmd = [
        sys.executable,
        str(GENERATOR),
        str(source),
        str(out_dir),
    ]
    if detail:
        cmd += ["--detail", str(detail)]
    if high_thinking:
        cmd += ["--high-thinking"]

    print(f"\n  🤖 Running AI generator...")
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        print("  ⚠️  AI generation exited with errors — continuing with whatever was saved.")

    # Discover what was actually written and rename to stable ai-0N-*.* names
    renamed: dict[str, str] = {}
    for style, stem in AI_IMAGE_MAP.items():
        for ext in (".jpg", ".jpeg", ".png", ".webp"):
            raw = out_dir / f"generated-product-{style}{ext}"
            if raw.exists():
                final_name = f"{stem}{ext}"
                raw.rename(out_dir / final_name)
                renamed[style] = final_name
                break

    return renamed


def build_image_list(
    handle: str,
    source_files: list[str],
    ai_files: dict[str, str],
) -> tuple[str, list[str]]:
    """
    Return (thumbnail_file, [image_file, ...]) with lifestyle shot first.
    Falls back to first source image if no AI images were generated.
    """
    ordered_ai = [
        ai_files[s]
        for s in ["full-body-lifestyle", "spread-on-sofa", "folded-garment", "close-up-macro"]
        if s in ai_files
    ]
    all_images = ordered_ai + [f for f in source_files if f not in ordered_ai]
    thumbnail = all_images[0] if all_images else (source_files[0] if source_files else "")
    return thumbnail, all_images


# ── Seed TS generation ────────────────────────────────────────────────────────

SEED_TEMPLATE = '''\
/**
 * Auto-generated by product-studio/pipeline.py
 * Run with: yarn medusa exec src/scripts/seed-products-generated.ts
 *
 * Creates new products or updates images/thumbnail on existing ones.
 */

import {{ ExecArgs }} from "@medusajs/framework/types"
import {{ ContainerRegistrationKeys, Modules }} from "@medusajs/framework/utils"
import {{ createProductsWorkflow, updateProductsWorkflow }} from "@medusajs/medusa/core-flows"

const STOREFRONT_URL =
  process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:8000"

const img = (handle: string, file: string) =>
  `${{STOREFRONT_URL}}/products/${{handle}}/${{file}}`

const PRODUCTS = {products_json}

const SIZES = ["S/M", "L/XL", "One Size"]

export default async function seedGeneratedProducts({{ container }}: ExecArgs) {{
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const query = container.resolve(ContainerRegistrationKeys.QUERY)
  const productModuleService = container.resolve(Modules.PRODUCT)
  const salesChannelModuleService = container.resolve(Modules.SALES_CHANNEL)

  logger.info("Starting generated product seed...")

  const {{ data: regions }} = await query.graph({{
    entity: "region",
    fields: ["id", "name", "currency_code"],
  }})

  const gbRegion =
    regions.find(
      (r: any) =>
        r.currency_code === "gbp" ||
        r.name?.toLowerCase().includes("uk") ||
        r.name?.toLowerCase().includes("gb")
    ) || regions[0]

  if (!gbRegion) {{
    throw new Error("No region found. Run seed.ts first.")
  }}

  const salesChannels = await salesChannelModuleService.listSalesChannels()
  const defaultChannel = salesChannels[0]

  const existingCollections =
    await productModuleService.listProductCollections()
  const collectionMap: Record<string, string> = {{}}

  for (const [title, handle] of [
    ["Abayas", "abayas"],
    ["Kimonos", "kimonos"],
    ["New In", "new-in"],
  ]) {{
    const existing = existingCollections.find((c: any) => c.handle === handle)
    if (existing) {{
      collectionMap[title] = existing.id
    }} else {{
      const created = await productModuleService.createProductCollections({{
        title,
        handle,
      }})
      collectionMap[title] = (created as any).id ?? (created as any)[0]?.id
    }}
  }}

  const existingProducts = await productModuleService.listProducts()
  const existingByHandle: Record<string, any> = {{}}
  for (const p of existingProducts) existingByHandle[p.handle] = p

  for (const product of PRODUCTS) {{
    const existing = existingByHandle[product.handle]

    if (existing) {{
      logger.info(`  Updating images: ${{product.title}}`)
      await updateProductsWorkflow(container).run({{
        input: {{
          selector: {{ id: existing.id }},
          update: {{
            thumbnail: product.thumbnail,
            images: product.images.map((url) => ({{ url }})),
          }},
        }},
      }})
      logger.info(`  ✓ Updated: ${{product.title}}`)
      continue
    }}

    logger.info(`  Creating: ${{product.title}}`)

    const {{ result }} = await createProductsWorkflow(container).run({{
      input: {{
        products: [
          {{
            title: product.title,
            handle: product.handle,
            subtitle: product.subtitle,
            description: product.description,
            status: "published" as const,
            thumbnail: product.thumbnail,
            images: product.images.map((url) => ({{ url }})),
            collection_id: collectionMap[product.collection],
            categories: [],
            tags: [],
            options: [{{ title: "Size", values: SIZES }}],
            variants: (product.sizes ?? SIZES).map((size) => ({{
              title: size,
              sku: `${{product.handle}}-${{size.toLowerCase().replace("/", "-")}}`,
              options: {{ Size: size }},
              prices: [
                {{
                  amount: product.price_gbp,
                  currency_code: "gbp",
                  rules: {{ region_id: gbRegion.id }},
                }},
              ],
              manage_inventory: false,
            }})),
            sales_channels: defaultChannel ? [{{ id: defaultChannel.id }}] : [],
          }},
        ],
      }},
    }})

    logger.info(`  ✓ Created: ${{result[0].title}}`)
  }}

  logger.info("✅ Generated product seed complete!")
}}
'''


def render_product_ts(
    meta: dict,
    handle: str,
    thumbnail: str,
    images: list[str],
) -> dict:
    """Return a plain dict that will be JSON-serialised into the TS PRODUCTS array."""
    sizes = meta.get("sizes", ["S/M", "L/XL", "One Size"])
    return {
        "title": meta["title"],
        "handle": handle,
        "subtitle": meta.get("subtitle", ""),
        "description": meta.get("description", ""),
        "collection": meta.get("collection", "New In"),
        "price_gbp": meta.get("price_gbp", 0),
        "sizes": sizes,
        "_thumbnail": thumbnail,
        "_images": images,
    }


def generate_seed_ts(products_data: list[dict]) -> None:
    """Write backend/src/scripts/seed-products-generated.ts"""

    ts_lines = ["[\n"]
    for p in products_data:
        handle = p["handle"]
        thumb = p["_thumbnail"]
        imgs = p["_images"]
        ts_lines.append("  {\n")
        ts_lines.append(f'    title: {json.dumps(p["title"])},\n')
        ts_lines.append(f'    handle: {json.dumps(p["handle"])},\n')
        ts_lines.append(f'    subtitle: {json.dumps(p.get("subtitle", ""))},\n')
        ts_lines.append(f'    description: {json.dumps(p.get("description", ""))},\n')
        ts_lines.append(f'    collection: {json.dumps(p.get("collection", "New In"))},\n')
        ts_lines.append(f'    price_gbp: {p.get("price_gbp", 0)},\n')
        ts_lines.append(f'    sizes: {json.dumps(p.get("sizes", ["S/M", "L/XL", "One Size"]))},\n')
        ts_lines.append(f'    thumbnail: img({json.dumps(handle)}, {json.dumps(thumb)}),\n')
        ts_lines.append(f'    images: [\n')
        for img_file in imgs:
            ts_lines.append(f'      img({json.dumps(handle)}, {json.dumps(img_file)}),\n')
        ts_lines.append("    ],\n")
        ts_lines.append("  },\n")
    ts_lines.append("]")

    products_ts = "".join(ts_lines)

    content = SEED_TEMPLATE.format(products_json=products_ts)
    SEED_OUT.write_text(content)
    print(f"\n📄 Seed script written to: {SEED_OUT}")
    print(f"   Run with: yarn medusa exec src/scripts/seed-products-generated.ts")


# ── Main ──────────────────────────────────────────────────────────────────────

def process_product(handle: str, skip_ai: bool = False, high_thinking: bool = False) -> dict | None:
    product_dir = INPUT_DIR / handle

    if not product_dir.is_dir():
        print(f"❌ No input directory found for: {handle}")
        return None

    meta_path = product_dir / "product.json"
    if not meta_path.exists():
        print(f"❌ Missing product.json in: {product_dir}")
        return None

    meta = json.loads(meta_path.read_text())
    effective_handle = meta.get("handle", handle)

    print(f"\n{'='*60}")
    print(f"  Product: {meta.get('title', handle)}")
    print(f"  Handle:  {effective_handle}")
    print(f"{'='*60}")

    source = find_image(product_dir, REQUIRED_SOURCE)
    if not source:
        print(f"❌ No 01-front image found in {product_dir}")
        return None

    detail = find_image(product_dir, OPTIONAL_DETAIL)

    out_dir = STOREFRONT_PRODUCTS / effective_handle
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n  📁 Copying source images → {out_dir}")
    source_files = copy_source_images(product_dir, out_dir)
    print(f"  Copied: {source_files}")

    ai_files: dict[str, str] = {}
    if not skip_ai:
        ai_files = run_ai_generation(source, detail, out_dir, high_thinking=high_thinking)
        if ai_files:
            print(f"  AI images: {list(ai_files.values())}")
        else:
            print("  ⚠️  No AI images generated.")
    else:
        # Detect already-generated AI images in the output directory
        style_file_map = {
            "folded-garment":      "ai-01-folded",
            "full-body-lifestyle": "ai-02-lifestyle",
            "close-up-macro":      "ai-03-macro",
            "spread-on-sofa":      "ai-04-sofa",
        }
        for style, stem in style_file_map.items():
            for ext in (".jpg", ".jpeg", ".png", ".webp"):
                if (out_dir / f"{stem}{ext}").exists():
                    ai_files[style] = f"{stem}{ext}"
                    break
        if ai_files:
            print(f"  Found existing AI images: {list(ai_files.values())}")

    thumbnail, images = build_image_list(effective_handle, source_files, ai_files)

    return {
        "title": meta["title"],
        "handle": effective_handle,
        "subtitle": meta.get("subtitle", ""),
        "description": meta.get("description", ""),
        "collection": meta.get("collection", "New In"),
        "price_gbp": meta.get("price_gbp", 0),
        "sizes": meta.get("sizes", ["S/M", "L/XL", "One Size"]),
        "_thumbnail": thumbnail,
        "_images": images,
    }


def main():
    parser = argparse.ArgumentParser(description="NikooLife Product Studio Pipeline")
    parser.add_argument(
        "handle",
        nargs="?",
        help="Product handle to process (omit for all products in input/)",
    )
    parser.add_argument(
        "--skip-ai",
        action="store_true",
        help="Copy source images only; skip AI generation",
    )
    parser.add_argument(
        "--high-thinking",
        action="store_true",
        help="Use HIGH thinking level for better text removal and spatial reasoning (slower)",
    )
    parser.add_argument(
        "--no-seed",
        action="store_true",
        help="Skip writing the seed TS file",
    )
    args = parser.parse_args()

    if not INPUT_DIR.exists():
        print(f"❌ Input directory not found: {INPUT_DIR}")
        sys.exit(1)

    if args.handle:
        handles = [args.handle]
    else:
        handles = sorted(
            d.name for d in INPUT_DIR.iterdir()
            if d.is_dir() and not d.name.startswith(".")
        )
        if not handles:
            print(f"No product directories found in {INPUT_DIR}")
            sys.exit(0)

    print(f"🚀 Processing {len(handles)} product(s): {handles}")

    products_data = []
    for handle in handles:
        data = process_product(handle, skip_ai=args.skip_ai, high_thinking=args.high_thinking)
        if data:
            products_data.append(data)

    if products_data and not args.no_seed:
        generate_seed_ts(products_data)

    print(f"\n✅ Pipeline complete. {len(products_data)}/{len(handles)} products processed.")


if __name__ == "__main__":
    main()
